/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BimViewer {
        /**
          * Id of the canvas to render the model
         */
        "canvasid": string;
        /**
          * Path of XKT file to load
         */
        "xktsrc": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBimViewerElement extends Components.BimViewer, HTMLStencilElement {
    }
    var HTMLBimViewerElement: {
        prototype: HTMLBimViewerElement;
        new (): HTMLBimViewerElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "bim-viewer": HTMLBimViewerElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BimViewer {
        /**
          * Id of the canvas to render the model
         */
        "canvasid"?: string;
        /**
          * Path of XKT file to load
         */
        "xktsrc"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "bim-viewer": BimViewer;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bim-viewer": LocalJSX.BimViewer & JSXBase.HTMLAttributes<HTMLBimViewerElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
